name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      # - name: Build Windows x64
      #   run: "zig build -Dtarget=x86_64-windows -Doptimize=ReleaseSafe -Dexe_name=ejson_runner_windows_x64"

      - name: Build Linux x64
        run: "zig build -Dtarget=x86_64-linux -Doptimize=ReleaseSafe -Dexe_name=ejson_runner_linux_x64"

      - name: Build Linux aarch64
        run: "zig build -Dtarget=aarch64-linux -Doptimize=ReleaseSafe -Dexe_name=ejson_runner_linux_aarch64"

      - name: Build Mac arm64
        run: "zig build -Dtarget=aarch64-macos -Doptimize=ReleaseSafe -Dexe_name=ejson_runner_macos_arm64"

      - name: Generate Checksums
        run: |
          cd ./zig-out/bin
          sha256sum ejson_runner_linux_x64 ejson_runner_linux_aarch64 ejson_runner_macos_arm64 > checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./zig-out/bin/ejson_runner_linux_x64
            ./zig-out/bin/ejson_runner_linux_aarch64
            ./zig-out/bin/ejson_runner_macos_arm64
            ./zig-out/bin/checksums.txt

